#!/bin/bash

cd "$HOME"

echo "Initializing submodules"
yadm submodule update --recursive --init

echo "Setting up SSH client"
if [[ ! -d "${HOME}/.ssh" ]]; then
    mkdir -p $HOME/.ssh
fi

if [[ ! -f "${HOME}/.ssh/id_rsa" ]]; then
    ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)"
fi

eval "$(ssh-agent -s)"

if [[ ! -f "${HOME}/.ssh/config" ]]; then
    cat << EOF > "${HOME}/.ssh/config"
Host *
  AddKeysToAgent yes
  # UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
EOF
fi

ssh-add ${HOME}/.ssh/id_rsa

echo "**********************************"
echo "This is your new public key:"
ssh-add -L
echo "**********************************"


echo "Setting up Git"
echo "Enter the name to use for git author:"
read git_name
echo "Enter the email to use for git author:"
read git_email

git config --global user.name "${git_name}"
git config --global user.email "${git_email}"

system_name=$(uname -s)
case $system_name in
    Linux)
        echo "you're using Linux"

	if [[ -f ${HOME}/.config/aptfile ]]; then
	  echo "Installing apt packages from aptfile"
          sudo apt update && sudo apt install -y $(cat ${HOME}/.config/aptfile | tr "\n" " ")
	fi
        ;;

    Darwin)
        echo "you're using Mac"

        if ! command -v brew > /dev/null 2>&1 ; then
            echo "Installing Homebrew.  Beer memes commencing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        fi

        echo "Installing default brew bundle"
        brew bundle --file=~/.config/yadm/brewfile

	if [ ! -d ${HOME}/.zplug ]; then
            git clone https://github.com/zplug/zplug ${HOME}/.zplug
	fi

        ;;

    *)
        echo "you're using an unsupported operating system"
        exit 1
        ;;

esac

echo "Adding origin URL to git remote"
yadm remote set-url origin "https://github.com/TimSpence/dotfiles.git"
yadm remote set-url --push origin "git@github.com:TimSpence/dotfiles.git"

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

