#!/bin/bash

truecolor_check() {
    awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
            printf "\033[48;2;%d;%d;%dm", r,g,b;
            printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            printf "%s\033[0m", substr(s,colnum+1,1);
        }
    printf "\n";
    }'
}

check_all_the_things() {
    # https://gist.github.com/XVilka/8346728#gistcomment-3191656
    echo -ne \\e\[1\;3\;4:3\;5\;53\;38\;2\;255\;127\;0\;58\;2\;0\;48\;255\;48\;2\;255\;0\;{0..255..8}mX \\e\[0m\\n
}

is_linux() {
  [[ $(uname) == 'Linux' ]];
}

is_osx() {
  [[ $(uname) == 'Darwin' ]];
}

cd "$HOME"

if [ ! -d git-clones ]; then
    mkdir -p git-clones
fi

if is_osx; then
    if [ ! -d $HOME/git-clones/fonts ]; then
        echo Installing Powerline fonts
        cd git-clones
        git clone https://github.com/powerline/fonts.git --depth=1
        cd fonts
        sh -x ./install.sh
        cd $HOME
    fi
fi

echo "Switching shell to zsh"
if which zsh; then
    chsh -s $(which zsh)
fi

echo "Checking for truecolor support"
echo "Your terminal will render a rainbow if supported"
truecolor_check


echo "Initializing submodules"
yadm submodule update --recursive --init

echo "Setting up SSH client"
if [[ ! -d "${HOME}/.ssh" ]]; then
    mkdir -p $HOME/.ssh
fi

if [[ ! -f "${HOME}/.ssh/id_rsa" ]]; then
    ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)"
fi

eval "$(ssh-agent -s)"

if [[ ! -f "${HOME}/.ssh/config" ]]; then
    cat << EOF > "${HOME}/.ssh/config"
Host *
  AddKeysToAgent yes
  # UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
EOF
fi

ssh-add ${HOME}/.ssh/id_rsa

echo "**********************************"
echo "This is your new public key:"
ssh-add -L
echo "**********************************"


echo "Setting up Git"
echo "Enter the name to use for git author:"
read git_name
echo "Enter the email to use for git author:"
read git_email

git config --global user.name "${git_name}"
git config --global user.email "${git_email}"

system_name=$(uname -s)
case $system_name in
    Linux)
        echo "you're using Linux"

	if [[ -f ${HOME}/.config/aptfile ]]; then
	  echo "Installing apt packages from aptfile"
          sudo apt update && sudo apt install -y $(cat ${HOME}/.config/aptfile | tr "\n" " ")
	fi
        ;;

    Darwin)
        echo "you're using Mac"

        if ! command -v brew > /dev/null 2>&1 ; then
            echo "Installing Homebrew.  Beer memes commencing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        fi

        echo "Installing default brew bundle"
        brew bundle --file=~/.config/yadm/brewfile

        ;;

    *)
        echo "you're using an unsupported operating system"
        exit 1
        ;;

esac

if [ ! -d ${HOME}/.zplug ]; then
   git clone https://github.com/zplug/zplug ${HOME}/.zplug
fi

echo "Adding origin URL to git remote"
yadm remote set-url origin "https://github.com/TimSpence/dotfiles.git"
yadm remote set-url --push origin "git@github.com:TimSpence/dotfiles.git"

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

